import { ForecastResponse, AirQualityResponse, AirQualityMapPoint, HistoricalSunResponse, WindGridCache } from './types';

export const state = {
  currentData: null as ForecastResponse | null,
  currentLat: 0,
  currentLon: 0,
  currentLocName: '',
  currentAirQuality: null as AirQualityResponse | null,
  currentSunHistory: undefined as HistoricalSunResponse | null | undefined,
  selectedDayIndex: 0,
  currentCoords: null as { lat: number; lon: number } | null,
  airQualityMapPoints: [] as AirQualityMapPoint[],
  airQualityMapCacheKey: '',
  airQualityMapRequestId: 0,
  weatherRequestId: 0,
  tempUnit: (localStorage.getItem('tempUnit') as 'C' | 'F') || 'C',
  skylinesByCity: {} as Record<string, string>,
  currentEnv: 'rural' as 'city' | 'suburb' | 'rural' | 'skyline' | 'none',
  airQualityMapState: { latitude: 0, longitude: 0, zoom: 8, panX: 0, panY: 0 },
  windGridCache: null as WindGridCache | null,
  forecastResizeTimer: undefined as number | undefined,
  windAnimId: 0 as any,
  lastWind: null as any,
  mapLayer: 'wind' as 'wind' | 'precip' | 'temp',
  airQualityMapRenderFrame: 0 as any,
  airQualityPointerId: -1 as any,
  airQualityPointerX: 0,
  airQualityPointerY: 0,
  airGridCache: null as any,
  windZoom: 6,
  tileZoom: 6,
  airQualityMapView: null as any,
  airQualityResizeTimer: undefined as number | undefined,
  savedWindowScrollY: 0,
  savedDailyScrollLeft: 0,
  averageValues: null as any
};